/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmptyNotes: typeof import('./src/components/EmptyNotes.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBodyContent: typeof import('./src/components/SideBodyContent.vue')['default']
    SideFooterContent: typeof import('./src/components/SideFooterContent.vue')['default']
    SideHeaderContent: typeof import('./src/components/SideHeaderContent.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  }
}
